name: Deploy to cloudtype
on:
  push:
    branches:
      - main
    paths:
      - "server/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: code-to-give/code-to-give
          stage: main
          yaml: |
            name: code-to-give
            app: java@17
            options:
              ports: 8080
              healthz: /ping
              env: 
                - name: AWS_ACCESS_KEY_ID
                  value: ${{ secrets.AWS_ACCESS_KEY_ID }}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                - name : AWS_REGION
                  value: ${{ secrets.AWS_REGION }}
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
                - name: AZURE_API_KEY
                  value: ${{ secrets.AZURE_API_KEY }}
                - name : AZURE_OPENAI_CHAT_DEPLOYMENT
                  value: dev
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot